# Generated by Django 5.0.6 on 2025-12-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Final Matemática', max_length=200)),
                ('pin_profesor', models.CharField(help_text='PIN para cerrar sesión', max_length=4)),
                ('cantidad_faciles', models.PositiveIntegerField(default=5)),
                ('cantidad_medias', models.PositiveIntegerField(default=3)),
                ('cantidad_dificiles', models.PositiveIntegerField(default=2)),
                ('activo', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='KioskSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_nombre', models.CharField(max_length=200)),
                ('alumno_dni', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('examen_snapshot', models.JSONField(default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom_exams.kioskconfig')),
            ],
        ),
    ]
