# Generated by Django 5.0.6 (simulado para S0b)
# Este archivo le dice a Django CÓMO construir las tablas para la app 'tenancy'.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # Esta migración depende de que el modelo de Usuarios de Django ya exista.
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Crea la tabla 'tenancy_tenant'
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Institución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institución (Tenant)',
                'verbose_name_plural': 'Instituciones (Tenants)',
            },
        ),
        
        # 2. Crea la tabla 'tenancy_tenantmembership'
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin del Tenant'), ('docente', 'Docente'), ('auxiliar', 'Auxiliar/Corrector'), ('alumno', 'Alumno')], max_length=20, verbose_name='Rol')),
                ('legajo', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Legajo')),
                ('dni_hash', models.CharField(blank=True, db_index=True, max_length=256, null=True, verbose_name='DNI Hash (SHA-256)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenancy.tenant', verbose_name='Institución')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresía de Institución',
                'verbose_name_plural': 'Membresías de Institución',
                # Define la restricción de que un usuario solo puede tener un rol por tenant
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
