# Generated by Django 5.0.6 (simulado para S1)
# Este archivo le dice a Django CÓMO construir las tablas para la app 'exams'.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # Depende de que 'tenancy' (S0b) y 'auth' (Django) ya existan
    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Crea la tabla 'exams_item'
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('MC', 'Opción Múltiple (MC)'), ('SHORT', 'Respuesta Corta'), ('CASE', 'Estudio de Caso')], default='MC', max_length=10, verbose_name='Tipo de Ítem')),
                ('tags', models.CharField(blank=True, help_text='Escribe las etiquetas separadas por coma (ej: algebra, ecuaciones, primer_año)', max_length=255, verbose_name='Etiquetas')),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='Nivel de dificultad (1-5)', verbose_name='Dificultad')),
                ('stem', models.TextField(verbose_name='Enunciado (Stem)')),
                ('options', models.JSONField(blank=True, help_text="Formato JSON: [{'text': 'Opción A', 'correct': True}, ...]", null=True, verbose_name='Opciones (para MC)')),
                ('case_content', models.TextField(blank=True, help_text="El texto/contexto principal para un ítem de 'Estudio de Caso'.", null=True, verbose_name='Contenido del Caso (si aplica)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Docente)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Ítem de Pregunta',
                'verbose_name_plural': 'Banco de Ítems',
            },
        ),
        # 2. Crea la tabla 'exams_exam'
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Examen')),
                ('shuffle_items', models.BooleanField(default=True, verbose_name='Mezclar orden de preguntas (RA-02)')),
                ('shuffle_options', models.BooleanField(default=True, verbose_name='Mezclar opciones de MC (RA-03)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_authored', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Docente)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='tenancy.tenant', verbose_name='Institución')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
            },
        ),
        # 3. Crea la tabla 'exams_examitemlink'
        migrations.CreateModel(
            name='ExamItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Puntaje')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.item')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('exam', 'item')},
            },
        ),
        # 4. Asigna el "through" (campo intermedio)
        migrations.AddField(
            model_name='exam',
            name='items',
            field=models.ManyToManyField(related_name='exams', through='exams.ExamItemLink', to='exams.item', verbose_name='Ítems Incluidos'),
        ),
    ]
