# Generated by Django 5.0.6 (simulado para S1c - Bugfix 2)
# Esta migración añade la restricción "unique_together" y actualiza la terminología

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('tenancy', '0001_initial'),
        # Asegura que dependemos del modelo de usuario base
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Banco de Preguntas'},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'stem')},
        ),
    ]
