# Generated by Django 5.0.6 (simulado para S1c - Bugfix 2)
# Esta migración añade la restricción "unique_together"

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'stem')},
        ),
    ]
