# Generated by Django 5.0.6 on 2025-11-14 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_unique_item_stem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='access_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID único para el enlace de acceso del alumno', unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el examen fue publicado', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], db_index=True, default='draft', max_length=10),
        ),
    ]
